// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_messages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_2eproto;
namespace car {
class ControlCommand;
struct ControlCommandDefaultTypeInternal;
extern ControlCommandDefaultTypeInternal _ControlCommand_default_instance_;
class Telemetry;
struct TelemetryDefaultTypeInternal;
extern TelemetryDefaultTypeInternal _Telemetry_default_instance_;
}  // namespace car
PROTOBUF_NAMESPACE_OPEN
template<> ::car::ControlCommand* Arena::CreateMaybeMessage<::car::ControlCommand>(Arena*);
template<> ::car::Telemetry* Arena::CreateMaybeMessage<::car::Telemetry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace car {

// ===================================================================

class ControlCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:car.ControlCommand) */ {
 public:
  inline ControlCommand() : ControlCommand(nullptr) {}
  ~ControlCommand() override;
  explicit PROTOBUF_CONSTEXPR ControlCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ControlCommand(const ControlCommand& from);
  ControlCommand(ControlCommand&& from) noexcept
    : ControlCommand() {
    *this = ::std::move(from);
  }

  inline ControlCommand& operator=(const ControlCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlCommand& operator=(ControlCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlCommand* internal_default_instance() {
    return reinterpret_cast<const ControlCommand*>(
               &_ControlCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ControlCommand& a, ControlCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ControlCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ControlCommand& from) {
    ControlCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "car.ControlCommand";
  }
  protected:
  explicit ControlCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kSteerFieldNumber = 2,
  };
  // float speed = 1;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // float steer = 2;
  void clear_steer();
  float steer() const;
  void set_steer(float value);
  private:
  float _internal_steer() const;
  void _internal_set_steer(float value);
  public:

  // @@protoc_insertion_point(class_scope:car.ControlCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float speed_;
    float steer_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// -------------------------------------------------------------------

class Telemetry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:car.Telemetry) */ {
 public:
  inline Telemetry() : Telemetry(nullptr) {}
  ~Telemetry() override;
  explicit PROTOBUF_CONSTEXPR Telemetry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Telemetry(const Telemetry& from);
  Telemetry(Telemetry&& from) noexcept
    : Telemetry() {
    *this = ::std::move(from);
  }

  inline Telemetry& operator=(const Telemetry& from) {
    CopyFrom(from);
    return *this;
  }
  inline Telemetry& operator=(Telemetry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Telemetry& default_instance() {
    return *internal_default_instance();
  }
  static inline const Telemetry* internal_default_instance() {
    return reinterpret_cast<const Telemetry*>(
               &_Telemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Telemetry& a, Telemetry& b) {
    a.Swap(&b);
  }
  inline void Swap(Telemetry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Telemetry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Telemetry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Telemetry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Telemetry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Telemetry& from) {
    Telemetry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Telemetry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "car.Telemetry";
  }
  protected:
  explicit Telemetry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kHeadingFieldNumber = 3,
    kMeasuredSpeedFieldNumber = 4,
    kSteeringAngleFieldNumber = 5,
    kBatteryVoltageFieldNumber = 6,
    kTimestampNsFieldNumber = 7,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float heading = 3;
  void clear_heading();
  float heading() const;
  void set_heading(float value);
  private:
  float _internal_heading() const;
  void _internal_set_heading(float value);
  public:

  // float measured_speed = 4;
  void clear_measured_speed();
  float measured_speed() const;
  void set_measured_speed(float value);
  private:
  float _internal_measured_speed() const;
  void _internal_set_measured_speed(float value);
  public:

  // float steering_angle = 5;
  void clear_steering_angle();
  float steering_angle() const;
  void set_steering_angle(float value);
  private:
  float _internal_steering_angle() const;
  void _internal_set_steering_angle(float value);
  public:

  // float battery_voltage = 6;
  void clear_battery_voltage();
  float battery_voltage() const;
  void set_battery_voltage(float value);
  private:
  float _internal_battery_voltage() const;
  void _internal_set_battery_voltage(float value);
  public:

  // uint64 timestamp_ns = 7;
  void clear_timestamp_ns();
  uint64_t timestamp_ns() const;
  void set_timestamp_ns(uint64_t value);
  private:
  uint64_t _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:car.Telemetry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float heading_;
    float measured_speed_;
    float steering_angle_;
    float battery_voltage_;
    uint64_t timestamp_ns_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ControlCommand

// float speed = 1;
inline void ControlCommand::clear_speed() {
  _impl_.speed_ = 0;
}
inline float ControlCommand::_internal_speed() const {
  return _impl_.speed_;
}
inline float ControlCommand::speed() const {
  // @@protoc_insertion_point(field_get:car.ControlCommand.speed)
  return _internal_speed();
}
inline void ControlCommand::_internal_set_speed(float value) {
  
  _impl_.speed_ = value;
}
inline void ControlCommand::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:car.ControlCommand.speed)
}

// float steer = 2;
inline void ControlCommand::clear_steer() {
  _impl_.steer_ = 0;
}
inline float ControlCommand::_internal_steer() const {
  return _impl_.steer_;
}
inline float ControlCommand::steer() const {
  // @@protoc_insertion_point(field_get:car.ControlCommand.steer)
  return _internal_steer();
}
inline void ControlCommand::_internal_set_steer(float value) {
  
  _impl_.steer_ = value;
}
inline void ControlCommand::set_steer(float value) {
  _internal_set_steer(value);
  // @@protoc_insertion_point(field_set:car.ControlCommand.steer)
}

// -------------------------------------------------------------------

// Telemetry

// float x = 1;
inline void Telemetry::clear_x() {
  _impl_.x_ = 0;
}
inline float Telemetry::_internal_x() const {
  return _impl_.x_;
}
inline float Telemetry::x() const {
  // @@protoc_insertion_point(field_get:car.Telemetry.x)
  return _internal_x();
}
inline void Telemetry::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Telemetry::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:car.Telemetry.x)
}

// float y = 2;
inline void Telemetry::clear_y() {
  _impl_.y_ = 0;
}
inline float Telemetry::_internal_y() const {
  return _impl_.y_;
}
inline float Telemetry::y() const {
  // @@protoc_insertion_point(field_get:car.Telemetry.y)
  return _internal_y();
}
inline void Telemetry::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Telemetry::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:car.Telemetry.y)
}

// float heading = 3;
inline void Telemetry::clear_heading() {
  _impl_.heading_ = 0;
}
inline float Telemetry::_internal_heading() const {
  return _impl_.heading_;
}
inline float Telemetry::heading() const {
  // @@protoc_insertion_point(field_get:car.Telemetry.heading)
  return _internal_heading();
}
inline void Telemetry::_internal_set_heading(float value) {
  
  _impl_.heading_ = value;
}
inline void Telemetry::set_heading(float value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:car.Telemetry.heading)
}

// float measured_speed = 4;
inline void Telemetry::clear_measured_speed() {
  _impl_.measured_speed_ = 0;
}
inline float Telemetry::_internal_measured_speed() const {
  return _impl_.measured_speed_;
}
inline float Telemetry::measured_speed() const {
  // @@protoc_insertion_point(field_get:car.Telemetry.measured_speed)
  return _internal_measured_speed();
}
inline void Telemetry::_internal_set_measured_speed(float value) {
  
  _impl_.measured_speed_ = value;
}
inline void Telemetry::set_measured_speed(float value) {
  _internal_set_measured_speed(value);
  // @@protoc_insertion_point(field_set:car.Telemetry.measured_speed)
}

// float steering_angle = 5;
inline void Telemetry::clear_steering_angle() {
  _impl_.steering_angle_ = 0;
}
inline float Telemetry::_internal_steering_angle() const {
  return _impl_.steering_angle_;
}
inline float Telemetry::steering_angle() const {
  // @@protoc_insertion_point(field_get:car.Telemetry.steering_angle)
  return _internal_steering_angle();
}
inline void Telemetry::_internal_set_steering_angle(float value) {
  
  _impl_.steering_angle_ = value;
}
inline void Telemetry::set_steering_angle(float value) {
  _internal_set_steering_angle(value);
  // @@protoc_insertion_point(field_set:car.Telemetry.steering_angle)
}

// float battery_voltage = 6;
inline void Telemetry::clear_battery_voltage() {
  _impl_.battery_voltage_ = 0;
}
inline float Telemetry::_internal_battery_voltage() const {
  return _impl_.battery_voltage_;
}
inline float Telemetry::battery_voltage() const {
  // @@protoc_insertion_point(field_get:car.Telemetry.battery_voltage)
  return _internal_battery_voltage();
}
inline void Telemetry::_internal_set_battery_voltage(float value) {
  
  _impl_.battery_voltage_ = value;
}
inline void Telemetry::set_battery_voltage(float value) {
  _internal_set_battery_voltage(value);
  // @@protoc_insertion_point(field_set:car.Telemetry.battery_voltage)
}

// uint64 timestamp_ns = 7;
inline void Telemetry::clear_timestamp_ns() {
  _impl_.timestamp_ns_ = uint64_t{0u};
}
inline uint64_t Telemetry::_internal_timestamp_ns() const {
  return _impl_.timestamp_ns_;
}
inline uint64_t Telemetry::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:car.Telemetry.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void Telemetry::_internal_set_timestamp_ns(uint64_t value) {
  
  _impl_.timestamp_ns_ = value;
}
inline void Telemetry::set_timestamp_ns(uint64_t value) {
  _internal_set_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:car.Telemetry.timestamp_ns)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace car

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_messages_2eproto
